name: mellowtel
description: "With Mellowtel, your users can share a fraction of their unused internet by using a transparent opt-in/out mechanism. Trusted partners access the internet through this network, and you get paid for it."
version: 0.0.4
homepage: https://www.mellowtel.dev/flutter/
repository: https://github.com/mellowtel-inc/mellowtel-flutter
issue_tracker: https://github.com/mellowtel-inc/mellowtel-flutter/issues

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

platforms:
  ios:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_windows: ^0.4.0
  flutter_inappwebview: ^6.0.0
  html2md: ^1.3.2
  web_socket_channel: ^2.4.0
  http: ^1.0.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.2.5
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
